services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  EnderLab\TranslatableEntityBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
  use Symfony\Contracts\Translation\TranslatorInterface: '@identity_translator'

  EnderLab\TranslatableEntityBundle\EventSubscriber\LocaleSubscriber:
    arguments:
      - '@identity_translator'
      - '@service_container'